---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "go-hello"
  name: "go-hello"
spec:
  ports:
  - name: "go-hello"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "go-hello"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "go-hello"
  name: "go-hello-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "go-hello"
  template:
    metadata:
      labels:
        app: "go-hello"
        logs: "true"
    spec:
      containers:
      - image: "ballerina/go_hello"
        imagePullPolicy: "Always"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "go-hello-deployment"
        ports:
        - containerPort: 8080
          name: "go-hello"
          protocol: "TCP"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "200m"
      nodeSelector: {}
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "go-hello"
  name: "go-hello-hpa"
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: "cpu"
      target:
        averageUtilization: 50
        type: "Utilization"
    type: "Resource"
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "go-hello-deployment"
