name: test_workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: "h1_h1_passthrough"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create local changes
      run: |
        echo "hello" | rev | cut -d/ -f1 | rev | sed -e "s/^"mi_"//" > image.txt
    - name: Commit files
      run: |
        git config --local user.email "ballerina-bot@ballerina.org"
        git config --local user.name "ballerina-bot"
        git commit -m "Bump VM Version" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BALLERINA_BOT_TOKEN }}
        branch: update-vm-image-${{ GITHUB.RUN_NUMBER }}
